---
abstract: 'Ordered hashes'
author:
  - 'Ken Williams <kwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tie-LLHash
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  perl: '5.006000'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Tie-LLHash
  repository: git://github.com/Xaerxess/Tie-LLHash.git
version: '1.004'
